// 初始化菜单数据
const menu = [
  {
    parent: "0",
    menuPath: "/digital",
    pathName: "digital",
    type: "dir",
    icon: "HomeOutlined",
    menuName: "系统中心",
    sort: 1,
    link: "",
    hidden: false,
    status: true,
    id: "1",
    childMenus: [
      {
        parent: "1",
        menuPath: "/digital/workspace",
        pathName: "digital-console",
        type: "menu",
        icon: "DashboardOutlined",
        menuName: "工作台",
        sort: 0,
        link: "",
        hidden: false,
        status: true,
        id: "1",
      },
      {
        parent: "1",
        menuPath: "/digital/appSystem",
        pathName: "appSystem",
        type: "menu",
        icon: "AppstoreOutlined",
        menuName: "应用管理",
        sort: 1,
        link: "",
        hidden: false,
        status: true,
        id: "2",
      },
      {
        parent: "1",
        menuPath: "/digital/department",
        pathName: "department",
        type: "menu",
        icon: "ApartmentOutlined",
        menuName: "部门管理",
        sort: 2,
        link: "",
        hidden: false,
        status: true,
        id: "3",
      },
      {
        parent: "1",
        menuPath: "/digital/role",
        pathName: "role",
        type: "menu",
        icon: "KeyOutlined",
        menuName: "角色管理",
        sort: 2,
        link: "",
        hidden: false,
        status: true,
        id: "4",
      },
      {
        parent: "1",
        menuPath: "/digital/staff",
        pathName: "staff",
        type: "menu",
        icon: "UserAddOutlined",
        menuName: "用户管理",
        sort: 2,
        link: "",
        hidden: false,
        status: true,
        id: "5",
      },
      {
        parent: "1",
        menuPath: "/digital/works",
        pathName: "works",
        type: "menu",
        icon: "DesktopOutlined",
        menuName: "岗位管理",
        sort: 2,
        link: "",
        hidden: false,
        status: true,
        id: "6",
      },
    ],
  },
];
export default menu;
