// 初始化菜单数据
const menu = [
  {
    parent: "0",
    menuUrl: "/digital",
    menuPath: "digital",
    type: "dir",
    icon: "HomeOutlined",
    menuName: "系统中心",
    sort: 1,
    link: "",
    hidden: false,
    status: true,
    applicationId: "1",
    childMenus: [
      {
        parent: "1",
        menuUrl: "/digital/workspace",
        menuPath: "digital-console",
        type: "menu",
        icon: "DashboardOutlined",
        menuName: "工作台",
        sort: 0,
        link: "",
        display: false,
        status: true,
        applicationId: "1",
      },
      {
        parent: "1",
        menuUrl: "/digital/appSystem",
        menuPath: "appSystem",
        type: "menu",
        icon: "AppstoreOutlined",
        menuName: "应用管理",
        sort: 1,
        link: "",
        display: false,
        status: true,
        applicationId: "2",
      },
      {
        parent: "1",
        menuUrl: "/digital/department",
        menuPath: "department",
        type: "menu",
        icon: "ApartmentOutlined",
        menuName: "部门管理",
        sort: 2,
        link: "",
        display: false,
        status: true,
        applicationId: "3",
      },
      {
        parent: "1",
        menuUrl: "/digital/role",
        menuPath: "role",
        type: "menu",
        icon: "KeyOutlined",
        menuName: "角色管理",
        sort: 2,
        link: "",
        display: false,
        status: true,
        applicationId: "4",
      },
      {
        parent: "1",
        menuUrl: "/digital/staff",
        menuPath: "staff",
        type: "menu",
        icon: "UserAddOutlined",
        menuName: "用户管理",
        sort: 2,
        link: "",
        display: false,
        status: true,
        applicationId: "5",
      },
      {
        parent: "1",
        menuUrl: "/digital/post",
        menuPath: "post",
        type: "menu",
        icon: "DesktopOutlined",
        menuName: "岗位管理",
        sort: 2,
        link: "",
        display: false,
        status: true,
        applicationId: "6",
      },
    ],
  },
];
export default menu;
